=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/schema/Collect.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="GlobalMetricSetting">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PluginInitParameter" minOccurs="0"/>
				<xs:element ref="ChangePluginInitParameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Sysoid" minOccurs="0" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
			<xs:attribute name="isEncrypt" use="optional" type="xs:string"></xs:attribute>
			<xs:attribute name="version" use="optional" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sysoid">
	</xs:element>
	<xs:element name="PluginInitParameter">
		<xs:complexType>
			<xs:attribute name="pluginid" type="xs:string" use="required"/>
			<xs:attribute name="parameterId" type="xs:string" use="required"/>
			<xs:attribute name="parameterValue" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChangePluginInitParameter">
		<xs:complexType>
			<xs:attribute name="pluginid" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="parameterId" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="parameterProperty" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="propertyValue" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="MetricPlugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PluginResultMetaInfo" minOccurs="0"/>
				<xs:element ref="PluginParameter"/>
				<xs:element ref="PluginDataHandlers" minOccurs="0"/>
				<xs:element ref="PluginDataConverter" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="metricid" use="required" type="xs:string">
			</xs:attribute>
			<xs:attribute name="pluginid" use="required" type="xs:string">
			</xs:attribute>
			<xs:attribute name="collectType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="WMI"/>
						<xs:enumeration value="TELNET"/>
						<xs:enumeration value="SSH"/>
						<xs:enumeration value="SNMP"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="MetricPlugins">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GlobalMetricSetting" minOccurs="0"/>
				<xs:element ref="PluginClassAliasList"/>
				<xs:element ref="MetricPlugin" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:keyref name="pluginDataConverterClassKeyref" refer="pluginClassAliasUnique">
			<xs:selector xpath=".//MetricPlugin/PluginDataConverter"/>
			<xs:field xpath="@classKey"/>
		</xs:keyref>
		<xs:keyref name="pluginDataHandlerClassKeyref" refer="pluginClassAliasUnique">
			<xs:selector xpath=".//MetricPlugin/PluginDataHandlers/PluginDataHandler"/>
			<xs:field xpath="@classKey"/>
		</xs:keyref>
		<xs:unique name="metricPluginUnique">
			<xs:selector xpath=".//MetricPlugin"/>
			<xs:field xpath="@metricid"/>
			<xs:field xpath="@pluginid"/>
		</xs:unique>
		<xs:unique name="pluginClassAliasUnique">
			<xs:selector xpath=".//PluginClassAliasList/PluginClassAlias"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginClassAlias">
		<xs:complexType>
			<xs:attribute name="id" use="required" type="xs:string"></xs:attribute>
			
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginClassAliasList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PluginClassAlias" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginDataConverter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="classKey" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="subInstConverter"></xs:enumeration>
						<xs:enumeration value="defaultConverter"></xs:enumeration>
						<xs:enumeration value="availableConverter"></xs:enumeration>
						<xs:enumeration value="processConverter"></xs:enumeration>
						
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginDataHandler">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded">
				</xs:element>
			</xs:sequence>
			<xs:attribute name="classKey" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="RegularFilter"/>
						<xs:enumeration value="selectProcessor"/>
						<xs:enumeration value="defaultProcessor"/>
						<xs:enumeration value="columnPasteProcessor"/>
						<xs:enumeration value="translateProcessor"/>
						<xs:enumeration value="tableConverter"></xs:enumeration>
						<xs:enumeration value="availableConverter"></xs:enumeration>
						<xs:enumeration value="SolarisNetStatProcessor"></xs:enumeration>
						<xs:enumeration value="ChangeRateProcessor"></xs:enumeration>
						<xs:enumeration value="rowFilterProcessor"></xs:enumeration>
						<xs:enumeration value="uptimeProcessor"></xs:enumeration>
						<xs:enumeration value="dateTimeProcessor"></xs:enumeration>
						<xs:enumeration value="FormatProcessor"></xs:enumeration>
						<xs:enumeration value="ResinActiveProcessor"></xs:enumeration>
						<xs:enumeration value="apacheProcessor"></xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		
	</xs:element>
	<xs:element name="PluginDataHandlers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PluginDataHandler" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginParameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ArrayType"/>
						<xs:enumeration value="MapType"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginResultMetaInfo">
		<xs:complexType>
			<xs:attribute name="columns" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/tools/4.1docs/vm/FusionComputeDataStore/collect.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetricPlugins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Collect.xsd">
	<GlobalMetricSetting isEncrypt="FALSE" version="4.1.0" />
	<PluginClassAliasList>
		<PluginClassAlias id="defaultProcessor" class="com.mainsteam.stm.plugin.common.DefaultResultSetProcessor" />
		<PluginClassAlias id="defaultConverter" class="com.mainsteam.stm.plugin.common.DefaultResultSetConverter" />
		<PluginClassAlias id="selectProcessor" class="com.mainsteam.stm.plugin.common.SelectResultSetProcessor" />
		<PluginClassAlias id="columnPasteProcessor" class="com.mainsteam.stm.plugin.common.ColumnPasteProcessor" />
		<PluginClassAlias id="RegularFilter" class="com.mainsteam.stm.plugin.common.RegularFilter" />
		<PluginClassAlias id="subInstConverter" class="com.mainsteam.stm.plugin.common.SubInstResultSetConverter" />
		<PluginClassAlias id="availableConverter" class="com.mainsteam.stm.plugin.common.AvailableConverter" />
		<PluginClassAlias id="tableConverter" class="com.mainsteam.stm.plugin.common.TableResultSetConverter" />
		<PluginClassAlias id="translateProcessor" class="com.mainsteam.stm.plugin.common.TranslateResultSetProcessor" />
		<PluginClassAlias id="ChangeRateProcessor" class="com.mainsteam.stm.plugin.common.ChangeRateProcessor" />
		<PluginClassAlias id="processConverter" class="com.mainsteam.stm.plugin.common.ProcessResultSetConverter" />
		<PluginClassAlias id="FormatProcessor" class="com.mainsteam.stm.plugin.common.FormatProcessor" />
		<PluginClassAlias id="rowFilterProcessor" class="com.mainsteam.stm.plugin.common.RowFilterProcessor" />
	</PluginClassAliasList>
    <MetricPlugin metricid="availability" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns="" />
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty" />
            <Parameter type="" key="COMMAND" value="getDataStoreAvailability" />
        </PluginParameter>
    </MetricPlugin>
	<MetricPlugin metricid="nameLabel" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreNameLabel" />
		</PluginParameter>
	</MetricPlugin>

	<MetricPlugin metricid="uuid" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreUuid" />
		</PluginParameter>
	</MetricPlugin>

	<MetricPlugin metricid="type" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreType" />
		</PluginParameter>
	</MetricPlugin>

<!-- 	<MetricPlugin metricid="shared" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreShared" />
		</PluginParameter>
	</MetricPlugin> -->
	
<!-- 	<MetricPlugin metricid="address" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreAddress" />
		</PluginParameter>
	</MetricPlugin> -->

	<MetricPlugin metricid="physicalSize" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStorePhysicalSize" />
		</PluginParameter>
	</MetricPlugin>

<MetricPlugin metricid="actualFreeSize" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStoreActualFreeSizeGB" />
		</PluginParameter>
	</MetricPlugin>
	
	<MetricPlugin metricid="physicalUtilisation" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStorePhysicalUtilisation" />
		</PluginParameter>
	</MetricPlugin>
	
	<MetricPlugin metricid="physicalRate" collectType="" pluginid="FusionComputePlugin">
		<PluginResultMetaInfo columns="" />
		<PluginParameter type="ArrayType">
			<Parameter value="uuid" key="uuid" type="ResourceProperty" />
			<Parameter type="" key="COMMAND" value="getDataStorePhysicalRate" />
		</PluginParameter>
	</MetricPlugin>
	
</MetricPlugins>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/4.1docs/vm/VMWareVCenter6.5/collect.xml
<?xml version="1.0" encoding="UTF-8"?>

<MetricPlugins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Collect.xsd">  
  <GlobalMetricSetting isEncrypt="FALSE" version="4.1.0"/>  
  <PluginClassAliasList> 
    <PluginClassAlias id="defaultProcessor" class="com.mainsteam.stm.plugin.common.DefaultResultSetProcessor"/>
    <PluginClassAlias id="defaultConverter" class="com.mainsteam.stm.plugin.common.DefaultResultSetConverter"/>
    <PluginClassAlias id="selectProcessor" class="com.mainsteam.stm.plugin.common.SelectResultSetProcessor"/>
    <PluginClassAlias id="columnPasteProcessor" class="com.mainsteam.stm.plugin.common.ColumnPasteProcessor"/>
    <PluginClassAlias id="RegularFilter" class="com.mainsteam.stm.plugin.common.RegularFilter"/>
    <PluginClassAlias id="subInstConverter" class="com.mainsteam.stm.plugin.common.SubInstResultSetConverter"/>
    <PluginClassAlias id="availableConverter" class="com.mainsteam.stm.plugin.common.AvailableConverter"/>
    <PluginClassAlias id="tableConverter" class="com.mainsteam.stm.plugin.common.TableResultSetConverter"/>
    <PluginClassAlias id="translateProcessor" class="com.mainsteam.stm.plugin.common.TranslateResultSetProcessor"/>
    <PluginClassAlias id="ChangeRateProcessor" class="com.mainsteam.stm.plugin.common.ChangeRateProcessor"/>
    <PluginClassAlias id="processConverter" class="com.mainsteam.stm.plugin.common.ProcessResultSetConverter"/>
    <PluginClassAlias id="FormatProcessor" class="com.mainsteam.stm.plugin.common.FormatProcessor"/>
    <PluginClassAlias id="rowFilterProcessor" class="com.mainsteam.stm.plugin.common.RowFilterProcessor"/>
  </PluginClassAliasList>  
  
  <MetricPlugin metricid="availability" collectType="" pluginid="vmPlugin6.5"> 
    <PluginResultMetaInfo columns=""/>  
    <PluginParameter type="ArrayType"> 
      <Parameter value="uuid" key="uuid" type="ResourceProperty"/>  
      <Parameter type="" key="COMMAND" value="com.mainsteam.stm.plugin.vmware.collector.VMWareVCenterCollector.getAvailability"/>
    </PluginParameter>
   <!--  
    <PluginDataHandlers> 
     <PluginDataHandler classKey="translateProcessor"> 
        <Parameter type="" key="" value="0,0;1"/> 
      </PluginDataHandler>
      <PluginDataHandler classKey="availableConverter"> 
      </PluginDataHandler> 
    </PluginDataHandlers>  -->
    
  </MetricPlugin> 

  <MetricPlugin metricid="Name" collectType="" pluginid="vmPlugin6.5"> 
    <PluginResultMetaInfo columns=""/>  
    <PluginParameter type="ArrayType"> 
      <Parameter type="" key="COMMAND" value="com.mainsteam.stm.plugin.vmware.collector.VMWareVCenterCollector.getName"/>
    </PluginParameter> 
  </MetricPlugin>  
  <MetricPlugin metricid="uuid" collectType="" pluginid="vmPlugin6.5"> 
    <PluginResultMetaInfo columns=""/>  
    <PluginParameter type="ArrayType"> 
      <Parameter type="" key="COMMAND" value="com.mainsteam.stm.plugin.vmware.collector.VMWareVCenterCollector.getUUID"/>
    </PluginParameter> 
  </MetricPlugin>  
  <MetricPlugin metricid="resourceTree" collectType="" pluginid="vmPlugin6.5"> 
    <PluginResultMetaInfo columns=""/>  
    <PluginParameter type="ArrayType"> 
      <Parameter type="" key="COMMAND" value="com.mainsteam.stm.plugin.vmware.collector.VMWareVCenterCollector.getResourceTree"/>
    </PluginParameter> 
  </MetricPlugin> 
</MetricPlugins>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/4.1docs/vm/XenSR/collect.xml
<?xml version="1.0" encoding="UTF-8"?>

<MetricPlugins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Collect.xsd">
    <GlobalMetricSetting isEncrypt="FALSE" version="4.1.0"/>
    <PluginClassAliasList>
        <PluginClassAlias id="defaultProcessor" class="com.mainsteam.stm.plugin.common.DefaultResultSetProcessor"/>
        <PluginClassAlias id="defaultConverter" class="com.mainsteam.stm.plugin.common.DefaultResultSetConverter"/>
        <PluginClassAlias id="selectProcessor" class="com.mainsteam.stm.plugin.common.SelectResultSetProcessor"/>
        <PluginClassAlias id="columnPasteProcessor" class="com.mainsteam.stm.plugin.common.ColumnPasteProcessor"/>
        <PluginClassAlias id="RegularFilter" class="com.mainsteam.stm.plugin.common.RegularFilter"/>
        <PluginClassAlias id="subInstConverter" class="com.mainsteam.stm.plugin.common.SubInstResultSetConverter"/>
        <PluginClassAlias id="availableConverter" class="com.mainsteam.stm.plugin.common.AvailableConverter"/>
        <PluginClassAlias id="tableConverter" class="com.mainsteam.stm.plugin.common.TableResultSetConverter"/>
        <PluginClassAlias id="translateProcessor" class="com.mainsteam.stm.plugin.common.TranslateResultSetProcessor"/>
        <PluginClassAlias id="ChangeRateProcessor" class="com.mainsteam.stm.plugin.common.ChangeRateProcessor"/>
        <PluginClassAlias id="processConverter" class="com.mainsteam.stm.plugin.common.ProcessResultSetConverter"/>
        <PluginClassAlias id="FormatProcessor" class="com.mainsteam.stm.plugin.common.FormatProcessor"/>
        <PluginClassAlias id="rowFilterProcessor" class="com.mainsteam.stm.plugin.common.RowFilterProcessor"/>
    </PluginClassAliasList>
    <MetricPlugin metricid="nameLabel" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRNameLabel"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="uuid" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRUuid"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="type" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRType"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="shared" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRShared"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="address" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRAddress"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="physicalSize" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRPhysicalSize"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="physicalUtilisation" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRPhysicalUtilisation"/>
        </PluginParameter>
    </MetricPlugin>
    <MetricPlugin metricid="physicalRate" collectType="" pluginid="XenPlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getSRPhysicalRate"/>
        </PluginParameter>
    </MetricPlugin>
</MetricPlugins>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/4.1docs/vm/FusionComputeCluster/collect.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetricPlugins xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Collect.xsd">
    <GlobalMetricSetting isEncrypt="FALSE" version="4.1.0"/>
    <PluginClassAliasList>
        <PluginClassAlias id="defaultProcessor" class="com.mainsteam.stm.plugin.common.DefaultResultSetProcessor"/>
        <PluginClassAlias id="defaultConverter" class="com.mainsteam.stm.plugin.common.DefaultResultSetConverter"/>
        <PluginClassAlias id="selectProcessor" class="com.mainsteam.stm.plugin.common.SelectResultSetProcessor"/>
        <PluginClassAlias id="columnPasteProcessor" class="com.mainsteam.stm.plugin.common.ColumnPasteProcessor"/>
        <PluginClassAlias id="RegularFilter" class="com.mainsteam.stm.plugin.common.RegularFilter"/>
        <PluginClassAlias id="subInstConverter" class="com.mainsteam.stm.plugin.common.SubInstResultSetConverter"/>
        <PluginClassAlias id="availableConverter" class="com.mainsteam.stm.plugin.common.AvailableConverter"/>
        <PluginClassAlias id="tableConverter" class="com.mainsteam.stm.plugin.common.TableResultSetConverter"/>
        <PluginClassAlias id="translateProcessor" class="com.mainsteam.stm.plugin.common.TranslateResultSetProcessor"/>
        <PluginClassAlias id="ChangeRateProcessor" class="com.mainsteam.stm.plugin.common.ChangeRateProcessor"/>
        <PluginClassAlias id="processConverter" class="com.mainsteam.stm.plugin.common.ProcessResultSetConverter"/>
        <PluginClassAlias id="FormatProcessor" class="com.mainsteam.stm.plugin.common.FormatProcessor"/>
        <PluginClassAlias id="rowFilterProcessor" class="com.mainsteam.stm.plugin.common.RowFilterProcessor"/>
    </PluginClassAliasList>

    <MetricPlugin metricid="availability" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterAvailability"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="nameLabel" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterNameLabel"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="uuid" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterUuid"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="clusterName" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterName"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="address" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterAddress"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="totalCpuSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterTotalCpuSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="usableCpuSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterUsableCpuSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="obligateCpuSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterObligateCpuSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="obligateCpuSizeRate" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterObligateCpuSizeRate"/>
        </PluginParameter>
    </MetricPlugin>


    <MetricPlugin metricid="totalMemSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterTotalMemSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="usableMemSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterUsableMemSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="obligateMemSize" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterObligateMemSize"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="obligateMemSizeRate" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterObligateMemSizeRate"/>
        </PluginParameter>
    </MetricPlugin>

    <!-- 	<MetricPlugin metricid="sysUpTime" collectType="" pluginid="FusionComputePlugin">
            <PluginResultMetaInfo columns="" />
            <PluginParameter type="ArrayType">
                <Parameter value="uuid" key="uuid" type="ResourceProperty" />
                <Parameter type="" key="COMMAND" value="getClusterSysUpTime" />
            </PluginParameter>
        </MetricPlugin>	 -->

    <MetricPlugin metricid="cpuRate" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterCpuRate"/>
        </PluginParameter>
    </MetricPlugin>

    <MetricPlugin metricid="memRate" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns=""/>
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty"/>
            <Parameter type="" key="COMMAND" value="getClusterMemRate"/>
        </PluginParameter>
    </MetricPlugin>

    <!-- <MetricPlugin metricid="throughput" collectType="" pluginid="FusionComputePlugin">
        <PluginResultMetaInfo columns="" />
        <PluginParameter type="ArrayType">
            <Parameter value="uuid" key="uuid" type="ResourceProperty" />
            <Parameter type="" key="COMMAND" value="getClusterThroughput" />
        </PluginParameter>
    </MetricPlugin>	 -->

</MetricPlugins>
