=== moutainhigh/stm-peng/stm_portal_3-master/capacity/tools/schema/Plugin.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="DefaultValue" type="xs:string"/>
	<xs:element name="HelpInfo" type="xs:string"/>
	<xs:element name="HideGroup" type="xs:string"/>
	<xs:element name="MaxActiveSession" type="xs:integer"/>
	<xs:element name="MaxidleSession" type="xs:integer"/>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="errorInfo" type="xs:string"/>
	<xs:element name="ObjectCacheTimeout" type="xs:integer"/>
	<xs:element name="Plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MaxActiveSession"/>
				<xs:element ref="MaxidleSession"/>
				<xs:element ref="SessionTTL"/>
				<xs:element ref="ObjectCacheTimeout"/>
				<xs:element ref="PluginInitParameters"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z0-9]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PluginInitParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="parameterIdUnique">
			<xs:selector xpath=".//parameter"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="SessionTTL" type="xs:integer"/>
	<xs:element name="ShowGroup" type="xs:string"/>
	<xs:element name="SupportValue">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Value"/>
				<xs:element ref="ShowGroup" minOccurs="0"/>
				<xs:element ref="HideGroup" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupportValues">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SupportValue" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Value" type="xs:string"/>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DefaultValue" minOccurs="0"/>
				<xs:element ref="SupportValues" minOccurs="0"/>
				<xs:element ref="HelpInfo" maxOccurs="unbounded"/>
				<xs:element ref="errorInfo" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z0-9]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="boxStyle" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="displayOrder" type="xs:integer" use="required"/>
			<xs:attribute name="isEdit" type="xs:boolean" use="required"/>
			<xs:attribute name="isDisplay" type="xs:boolean" use="required"/>
			<xs:attribute name="isSessionKey" type="xs:boolean"/>
			<xs:attribute name="valueValidate" type="xs:string"/>
			<xs:attribute name="mustInput" type="xs:boolean"/>
			<xs:attribute name="group" type="xs:string"/>
			<xs:attribute name="isPassword" type="xs:boolean"/>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="unit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="s"/>
						<xs:enumeration value="ms"/>
						<xs:enumeration value="m"/>
						<!-- 秒 -->
						<!-- 毫秒 -->
						<!-- 分 -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/plugins/NginxPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<Plugin version="1.0" id="NginxPlugin" name="NginxPlugin" 
	class="com.mainsteam.stm.plugin.nginx.NginxPluginSession"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../schema/Plugin.xsd">
	<MaxActiveSession>1</MaxActiveSession>
	<MaxidleSession>0</MaxidleSession>
	<SessionTTL>10000</SessionTTL>
	<ObjectCacheTimeout>30000</ObjectCacheTimeout>
	<PluginInitParameters>
		<parameter id="NginxGrpBox" boxStyle="GroupBox" name="Niginx服务器连接信息"
			displayOrder="1" isEdit="false" isDisplay="true" isSessionKey="false">
			<DefaultValue />
			<HelpInfo>Niginx服务器连接信息</HelpInfo>
		</parameter>
		<parameter id="IP" boxStyle="IPField" name="IP地址" displayOrder="1" valueValidate="/^([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])$/"
			isEdit="true" isDisplay="true" isSessionKey="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>待发现Niginx服务器的IP地址</HelpInfo>
			<errorInfo>请输入正确的IP格式，例如192.168.0.1</errorInfo>
		</parameter>
		<parameter id="PAGENAME" boxStyle="Input"  
			name="Niginx地址参数" displayOrder="4" isEdit="true" 
			isDisplay="true" mustInput="true" isSessionKey="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>Niginx地址参数，如 http://172.16.7.127/c-server-status</HelpInfo>
		</parameter>
		<parameter id="nginxPort" boxStyle="Input"  
			name="端口" displayOrder="4" isEdit="true" 
			isDisplay="true" mustInput="true" isSessionKey="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>默认80</HelpInfo>
		</parameter>
		<parameter id="nginxTimeout" boxStyle="Input" valueValidate="/\d+/" 
			name="Niginx超时时间" displayOrder="5" isEdit="true" 
			isDisplay="false" mustInput="false" isSessionKey="false">
			<DefaultValue>100</DefaultValue>
			<HelpInfo>Niginx超时时间</HelpInfo>
			<errorInfo>请输入整数</errorInfo>
		</parameter>
		</PluginInitParameters>
		</Plugin>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/plugins/IpmiPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<Plugin version="1.0" id="IpmiPlugin" name="IpmiPlugin"
	class="com.mainsteam.stm.plugin.ipmi.IpmiPluginSession" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../schema/Plugin.xsd">
	<!-- 最大活动session 数 -->
	<MaxActiveSession>1</MaxActiveSession>
	<!-- 最大空闲session 数 -->
	<MaxidleSession>0</MaxidleSession>
	<!-- session TTL -->
	<SessionTTL>10000</SessionTTL>
	<!-- 对象缓存的超时时间 -->
	<ObjectCacheTimeout>30000</ObjectCacheTimeout>

	<!-- 插件初始化参数，发现资源用 -->
	<PluginInitParameters>
		<parameter id="ipmiGrpBox" boxStyle="GroupBox" name="Ipmi连接信息"
			displayOrder="1" isEdit="false" isDisplay="true" isSessionKey="false">
			<HelpInfo>Ipmi连接信息</HelpInfo>
		</parameter>

		<!-- boxStyle输入框类型;displayOrder用于发现页面上输入项的显示顺序;isEdit可编辑;isDisplay可显示;isSessionKey区分采集会话 -->
		<parameter id="IP" boxStyle="IPField" name="IP地址"
			displayOrder="1" isEdit="true" isDisplay="true" isSessionKey="true"
			mustInput="true">
			<HelpInfo>待发现机器的IP地址</HelpInfo>
			<errorInfo>请输入正确的IP地址</errorInfo>
		</parameter>

		<!-- valueValidate校验输入内容合法性 -->
		<parameter id="port" boxStyle="Input"
			valueValidate="/^([0-9]|[1-9]\d|[1-9]\d{2}|[1-9]\d{3}|[1-5]\d{4}|6[0-4]\d{3}|65[0-4]\d{2}|655[0-2]\d|6553[0-5])$/"
			name="端口" displayOrder="2" isEdit="true" isDisplay="true" mustInput="true"
			isSessionKey="true">
			<!-- 默认值 -->
			<DefaultValue>623</DefaultValue>
			<!-- 帮助信息 -->
			<HelpInfo>Ipmi端口</HelpInfo>
			<!-- 错误提示 -->
			<errorInfo>请输入整数</errorInfo>
		</parameter>
		
		<parameter id="interface" boxStyle="OptionBox" name="接口"
			displayOrder="3" isEdit="true" isDisplay="true" mustInput="true"
			isSessionKey="true">
			<DefaultValue>lanplus</DefaultValue>
			<!-- radiobox和下拉框都有可选值 -->
			<SupportValues>
				<SupportValue>
					<!-- 可选值的名称和值 -->
					<Name>IPMI v2.0 RMCP+ LAN Interface</Name>
					<Value>lanplus</Value>
				</SupportValue>
				<SupportValue>
					<Name>IPMI v1.5 LAN Interface</Name>
					<Value>lan</Value>
				</SupportValue>
			</SupportValues>
			<HelpInfo>IPMI接口</HelpInfo>
		</parameter>

		<parameter id="level" boxStyle="OptionBox" name="特权级别"
			displayOrder="4" isEdit="true" isDisplay="true" mustInput="true"
			isSessionKey="true">
			<DefaultValue>ADMINISTRATOR</DefaultValue>
			<!-- radiobox和下拉框都有可选值 -->
			<SupportValues>
				<SupportValue>
					<!-- 可选值的名称和值 -->
					<Name>ADMINISTRATOR</Name>
					<Value>ADMINISTRATOR</Value>
				</SupportValue>
				<SupportValue>
					<Name>CALLBACK</Name>
					<Value>CALLBACK</Value>
				</SupportValue>
				<SupportValue>
					<Name>OPERATOR</Name>
					<Value>OPERATOR</Value>
				</SupportValue>
				<SupportValue>
					<Name>USER</Name>
					<Value>USER</Value>
				</SupportValue>
			</SupportValues>
			<HelpInfo>Ipmi连接特权级别</HelpInfo>
		</parameter>

		<parameter id="authtype" boxStyle="OptionBox" name="认证类型"
			displayOrder="5" isEdit="true" isDisplay="true" mustInput="true"
			isSessionKey="true">
			<DefaultValue>MD5</DefaultValue>
			<!-- radiobox和下拉框都有可选值 -->
			<SupportValues>
				<SupportValue>
					<!-- 可选值的名称和值 -->
					<Name>MD2</Name>
					<Value>MD2</Value>
				</SupportValue>
				<SupportValue>
					<Name>MD5</Name>
					<Value>MD5</Value>
				</SupportValue>
				<SupportValue>
					<Name>PASSWORD</Name>
					<Value>PASSWORD</Value>
				</SupportValue>
				<SupportValue>
					<Name>NONE</Name>
					<Value>NONE</Value>
				</SupportValue>
			</SupportValues>
			<HelpInfo>Ipmi连接认证类型</HelpInfo>
		</parameter>

		<parameter id="username" boxStyle="Input" name="用户名"
			displayOrder="6" isEdit="true" isDisplay="true" isSessionKey="true"
			mustInput="true">
			<HelpInfo>用户名</HelpInfo>
		</parameter>

		<parameter id="password" boxStyle="Input" name="密码"
			displayOrder="7" isEdit="true" isDisplay="true" isSessionKey="true"
			mustInput="true" isPassword="true">
			<HelpInfo>密码</HelpInfo>
		</parameter>
		
		<parameter id="KGValue" boxStyle="Input" name="KG值"
			displayOrder="8" isEdit="true" isDisplay="true" isSessionKey="true"
			mustInput="true" isPassword="true">
			<DefaultValue>000000</DefaultValue>
			<HelpInfo>KG值</HelpInfo>
		</parameter>
	</PluginInitParameters>
</Plugin>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/plugins/VmPlugin5.5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Plugin version="1.0" id="vmPlugin5.5" name="vmPlugin5.5"
	class="com.mainsteam.stm.plugin.vmware.ESXiPluginSessionFivePointFive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../schema/Plugin.xsd">
	<MaxActiveSession>1</MaxActiveSession>
	<MaxidleSession>0</MaxidleSession>
	<SessionTTL>10000</SessionTTL>
	<ObjectCacheTimeout>30000</ObjectCacheTimeout>
	<PluginInitParameters>
		<parameter id="SshGrpBox" boxStyle="GroupBox" name="主机连接信息"
			displayOrder="1" isEdit="false" isDisplay="true" isSessionKey="false">
			<DefaultValue />
			<HelpInfo>主机连接信息 vcenter6</HelpInfo>
		</parameter>

		<parameter id="IP" boxStyle="IPField" name="IP地址"
			displayOrder="1"
			valueValidate="/^([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])\.([0,1]?\d{0,2}|2[0-4]\d|25[0-5])$/"
			isEdit="true" isDisplay="true" isSessionKey="true" mustInput="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>待发现机器的IP地址</HelpInfo>
			<errorInfo>请输入正确的IP格式，例如192.168.0.1</errorInfo>
		</parameter>
		<parameter id="vmPort" boxStyle="Input" name="HTTPS端口" valueValidate="/^([0-9]|[1-9]\d|[1-9]\d{2}|[1-9]\d{3}|[1-5]\d{4}|6[0-4]\d{3}|65[0-4]\d{2}|655[0-2]\d|6553[0-5])$/"
			displayOrder="2" isEdit="true" isDisplay="false" mustInput="true"
			isSessionKey="true">
			<DefaultValue>443</DefaultValue>
			<HelpInfo>HTTPS端口，默认为43</HelpInfo>
			<errorInfo>请输入整数</errorInfo>
		</parameter>
		<parameter id="username" boxStyle="Input" name="用户名"
			displayOrder="3" isEdit="true" isDisplay="true" isSessionKey="true"
			type="user" mustInput="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>待发现机器的用户名</HelpInfo>
		</parameter>
		<parameter id="password" boxStyle="Input" name="密码"
			displayOrder="4" isEdit="true" isDisplay="true" isSessionKey="true"
			type="passsword" isPassword="true" mustInput="true">
			<DefaultValue></DefaultValue>
			<HelpInfo>待发现机器的密码</HelpInfo>
		</parameter>

	</PluginInitParameters>
</Plugin>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/plugins/HttpPlugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<Plugin version="1.0" id="HttpPlugin" name="HttpPlugin"
        class="com.mainsteam.stm.plugin.http.HttpPluginSession" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema/Plugin.xsd">
    <MaxActiveSession>1</MaxActiveSession>
    <MaxidleSession>0</MaxidleSession>
    <SessionTTL>10000</SessionTTL>
    <ObjectCacheTimeout>30000</ObjectCacheTimeout>

    <PluginInitParameters>

        <parameter id="HttpGrpBox" boxStyle="GroupBox" name="Http连接信息"
                   displayOrder="1" isEdit="false" isDisplay="true" isSessionKey="false">
            <DefaultValue/>
            <HelpInfo>Http连接信息</HelpInfo>
        </parameter>

        <parameter id="IP" boxStyle="IPField" name="IP地址"
                   displayOrder="1" isEdit="true" isDisplay="true" isSessionKey="true" mustInput="true">
            <DefaultValue/>
            <HelpInfo>IP地址</HelpInfo>
        </parameter>

        <parameter id="port" boxStyle="Input"
                   valueValidate="/^([0-9]|[1-9]\d|[1-9]\d{2}|[1-9]\d{3}|[1-5]\d{4}|6[0-4]\d{3}|65[0-4]\d{2}|655[0-2]\d|6553[0-5])$/"
                   name="端口" displayOrder="2" isEdit="true" isDisplay="true" mustInput="true" isSessionKey="true">
            <DefaultValue>443</DefaultValue>
            <HelpInfo>端口</HelpInfo>
            <errorInfo>请输入整数</errorInfo>
        </parameter>

        <parameter id="username" boxStyle="Input" name="用户名"
                   displayOrder="3" isEdit="true" isDisplay="true" isSessionKey="true">
            <DefaultValue/>
            <HelpInfo>用户名</HelpInfo>
        </parameter>

        <parameter id="password" boxStyle="Input" name="密码"
                   displayOrder="4" isEdit="true" isDisplay="true" isSessionKey="true" isPassword="true">
            <DefaultValue/>
            <HelpInfo>密码</HelpInfo>
        </parameter>

        <parameter id="protocol" boxStyle="OptionBox" name="协议"
                   displayOrder="5" isEdit="true" isDisplay="true" isSessionKey="true" mustInput="true">
            <DefaultValue>https</DefaultValue>
            <SupportValues>
                <SupportValue>
                    <Name>http</Name>
                    <Value>http</Value>
                </SupportValue>
                <SupportValue>
                    <Name>https</Name>
                    <Value>https</Value>
                </SupportValue>
            </SupportValues>
            <HelpInfo>协议</HelpInfo>
        </parameter>

        <parameter id="timeout" boxStyle="Input" name="超时时间" valueValidate="/\d+/"
                   displayOrder="10" isEdit="true" isDisplay="true" unit="ms">
            <DefaultValue>5000</DefaultValue>
            <HelpInfo>超时时间</HelpInfo>
        </parameter>

        <parameter id="serviceType" boxStyle="OptionBox" name="Http服务类型"
                   displayOrder="20" isEdit="true" isDisplay="false" isSessionKey="true" mustInput="true">
            <DefaultValue/>
            <SupportValues>
                <SupportValue>
                    <Name>CiscoTelePresenceMCU</Name>
                    <Value>CiscoTelePresenceMCU</Value>
                </SupportValue>
                <SupportValue>
                    <Name>CiscoTelePresenceServer</Name>
                    <Value>CiscoTelePresenceServer</Value>
                </SupportValue>
                <SupportValue>
                    <Name>CiscoTelePresenceSupervisor</Name>
                    <Value>CiscoTelePresenceSupervisor</Value>
                </SupportValue>
                <SupportValue>
                    <Name>CiscoTelePresenceConductor</Name>
                    <Value>CiscoTelePresenceConductor</Value>
                </SupportValue>
                <SupportValue>
                    <Name>CiscoTelePresenceContentServer</Name>
                    <Value>CiscoTelePresenceContentServer</Value>
                </SupportValue>
            </SupportValues>
            <HelpInfo>Http服务类型</HelpInfo>
        </parameter>

    </PluginInitParameters>
</Plugin>
