=== moutainhigh/stm-peng/stm_portal_3-master/capacity/tools/schema/Resource.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Capacity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SupportInfo" minOccurs="0"/>
				<xs:element ref="GlobalMetricSetting"/>
				<xs:element ref="Resource" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:keyref name="resourceIdKeyref" refer="resourceIdUnique">
			<xs:selector xpath=".//Resource"/>
			<xs:field xpath="@parentid"/>
		</xs:keyref>
		<xs:unique name="resourceIdUnique">
			<xs:selector xpath=".//Resource"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="DefaultMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1"/>
				<xs:enumeration value="min5"/>
				<xs:enumeration value="min10"/>
				<xs:enumeration value="min30"/>
				<xs:enumeration value="hour1"/>
				<xs:enumeration value="hour2"/>
				<xs:enumeration value="day1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GlobalDefaultMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1"/>
				<xs:enumeration value="min5"/>
				<xs:enumeration value="min10"/>
				<xs:enumeration value="min30"/>
				<xs:enumeration value="hour1"/>
				<xs:enumeration value="hour2"/>
				<xs:enumeration value="day1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GlobalIsAlert" type="xs:boolean"/>
	<xs:element name="GlobalIsEdit" type="xs:boolean"/>
	<xs:element name="GlobalIsMonitor" type="xs:boolean"/>
	<xs:element name="GlobalDefaultFlapping" type="xs:integer"/>
	<xs:element name="DefaultFlapping" type="xs:integer"/>
	<xs:element name="GlobalMetricSetting">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GlobalIsEdit"/>
				<xs:element ref="GlobalIsMonitor"/>
				<xs:element ref="GlobalDefaultMonitorFreq"/>
				<xs:element ref="GlobalsupportMonitorFreq"/>
				<xs:element ref="GlobalIsAlert"/>
				<xs:element ref="GlobalDefaultFlapping"/>
			</xs:all>
			<xs:attribute name="isEncrypt" type="xs:string" use="optional"/>
			<xs:attribute name="version" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GlobalsupportMonitorFreq" type="xs:string"/>
	<xs:element name="Instantiation">
		<xs:complexType>
			<xs:attribute name="InstanceId" type="xs:string" use="required"/>
			<xs:attribute name="InstanceName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsDisplay">
		<xs:complexType mixed="true">
			<xs:attribute name="displayOrder" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsEdit" type="xs:boolean"/>
	<xs:element name="IsMonitor" type="xs:boolean"/>
	<xs:element name="IsAlert" type="xs:boolean"/>
	<xs:element name="Metric">
		<xs:complexType>
			<xs:all>
				<xs:element ref="IsDisplay" minOccurs="0"/>
				<xs:element ref="IsMonitor" minOccurs="0"/>
				<xs:element ref="IsEdit" minOccurs="0"/>
				<xs:element ref="DefaultMonitorFreq" minOccurs="0"/>
				<xs:element ref="SupportMonitorFreq" minOccurs="0"/>
				<xs:element ref="Thresholds" minOccurs="0"/>
				<xs:element ref="DefaultFlapping" minOccurs="0"/>
				<xs:element ref="IsAlert" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"></xs:minLength>
						<xs:maxLength value="20"></xs:maxLength>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="style" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PerformanceMetric"/>
						<xs:enumeration value="AvailabilityMetric"/>
						<xs:enumeration value="InformationMetric"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="unit" type="xs:string" use="required"/>
			<xs:attribute name="group" type="xs:string" use="optional"/>
			<xs:attribute name="isTable" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Metrics">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Metric" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="metricid" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Resource">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Metrics"/>
				<xs:element ref="Properties"/>
				<xs:element ref="Instantiation"/>
			</xs:all>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="category" type="xs:string"/>
			<xs:attribute name="icon" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="parentid" type="xs:string"/>
			<xs:attribute name="autodiscovery" type="xs:boolean"/>
		</xs:complexType>
		<xs:key name="metricIdKey">
			<xs:selector xpath=".//Metrics/Metric"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="metricIdKeyref" refer="metricIdKey">
			<xs:selector xpath=".//Propertys/Property"/>
			<xs:field xpath="@metricid"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="SupportMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1,min5,hour1"/>
				<xs:enumeration value="min1,min5,hour1,day1"/>
				<xs:enumeration value="hour1,day1"/>
				<xs:enumeration value="hour1,hour2,day1"/>
				<xs:enumeration value="hour2,day1"/>
				<xs:enumeration value="min5,hour1"/>
				<xs:enumeration value="min5,hour1,day1"/>
				<xs:enumeration value="min5,min10,min30"/>
				<xs:enumeration value="min30,hour1"/>
				<xs:enumeration value="min30,hour1,hour2"/>
				<xs:enumeration value="sec30,min1,min5,min10,min30,hour1"/>
				<xs:enumeration value="min1,min5,min10,min30,hour1,day1"/>
				<xs:enumeration value="min1,min5,min10,min30,hour1,hour4,hour8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Thresholds">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Threshold" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Threshold">
		<xs:complexType>
			<xs:attribute name="operator" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value=">"/>
						<xs:enumeration value=">="/>
						<xs:enumeration value="&lt;>"/>
						<xs:enumeration value="&lt;"/>
						<xs:enumeration value="&lt;="/>
						<xs:enumeration value="="/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="defaultvalue" type="xs:string" use="optional"/>
			<xs:attribute name="stateid" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Indeterminate"/>
						<xs:enumeration value="Normal"/>
						<xs:enumeration value="Minor"/>
						<xs:enumeration value="Major"/>
						<xs:enumeration value="Critical"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupportInfo">
		<xs:complexType>
			<xs:all>
				<xs:element ref="SupportName"/>
				<xs:element ref="PreSupportVersion"/>
				<xs:element ref="ActualSupportVersion"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupportName" type="xs:string"/>
	<xs:element name="PreSupportVersion" type="xs:string"/>
	<xs:element name="ActualSupportVersion" type="xs:string"/>
</xs:schema>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/resources/general/process/resource.xml
<?xml version="1.0" encoding="UTF-8"?>

<Capacity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Resource.xsd">  
  
    <GlobalMetricSetting isEncrypt="TRUE"> 
    
        <GlobalIsEdit>false</GlobalIsEdit>  
    
        <GlobalIsMonitor>true</GlobalIsMonitor>  
    
        <GlobalDefaultMonitorFreq>day1</GlobalDefaultMonitorFreq>  
    
        <GlobalsupportMonitorFreq>min1,min5,min10,hour1,day1</GlobalsupportMonitorFreq>  
    
        <GlobalIsAlert>true</GlobalIsAlert>  
    
        <GlobalDefaultFlapping>1</GlobalDefaultFlapping> 
  
    </GlobalMetricSetting>  
  
    <Resource id="SklXU0d4Mk1Ram1Tb2dSTkkvY2svdz09" category="N0k3NUNzS2lGU3htZUpuc05jZHBBQT09" icon="NjEvYkpXV0FCM1k1SE9kZXlXbHFuUT09" name="SSH/Telnet" description="进程"> 
    
        <Metrics> 
      
            <Metric id="NFRRT3BMeEFmd3BkMWtsMEFYNEc0dz09" style="TDBUaHMrK3BZWXlhQmZoVXFZZERjenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="进程ID" description="进程ID" unit=""> 
        
                <IsDisplay displayOrder="UmhGRWpua2R6SURZaWpidXVBN2Nxdz09">VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsDisplay>  
        
                <IsMonitor>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>NHVBL0Y0NmhkYU50WHNzditxS3hYUT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>SHNiL3VCVUVqMXVJSjFRdG1XaDNuQT09</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping> 
      
            </Metric>
        
      
            <Metric id="K3A5eVhNYXd6RFpCeWlmVFY0bnJsQT09" style="TDBUaHMrK3BZWXlhQmZoVXFZZERjenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="进程名称" description="进程名称" unit=""> 
        
                <IsDisplay displayOrder="S0pnRThsN2pYR1piemxHL3VqMzhMQT09">VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsDisplay>  
        
                <IsMonitor>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>NHVBL0Y0NmhkYU50WHNzditxS3hYUT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>SHNiL3VCVUVqMXVJSjFRdG1XaDNuQT09</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping> 
      
            </Metric>
      
      
            <Metric id="Zk5lb0pYU01acTR6MVAzYUUzazRmZz09" style="TDBUaHMrK3BZWXlhQmZoVXFZZERjenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="IP地址" description="IP地址" unit="">
      	
                <IsDisplay displayOrder="azBBajMzZ3FFeG9CRjcwOTZPL0lPUT09">SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsDisplay>
      	
                <IsMonitor>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsMonitor>
      	
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>
      	
                <DefaultMonitorFreq>NHVBL0Y0NmhkYU50WHNzditxS3hYUT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>SHNiL3VCVUVqMXVJSjFRdG1XaDNuQT09</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping> 
      
            </Metric>
        
      
            <Metric id="bkVRdlhKd2d5bTNtb0ZKQ29kT1o5dz09" style="VzFQeGN6MkhDZTF5VVNhVVVELzR4RFpDUTQ3c2FXaEl4MDI0SjRyYi9hQT0=" name="进程状态" description="进程状态" unit=""> 
        
                <IsDisplay displayOrder="N1hzWURLbUYrRmFrU3NlQUdPUU9ydz09">SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsDisplay>  
        
                <IsMonitor>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>Q3g5Tk1ySnFkWEJEYjN1Smx4NWlyQT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>MGUvWmNTd1Mxai83anlydzFmeWtQVzlRSEs2aEdhNVFJVFlnVmhjWkppS0F2d2Uwc2N6aHl5UTE2U292K05pRA==</SupportMonitorFreq>  
        
                <IsAlert>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsAlert>  
        
                <DefaultFlapping>ZHdHVHJXSS9HN1F4UUZFOTMyam1Qdz09</DefaultFlapping> 
      
            </Metric>
       
      
            <Metric id="NTBZV0U2NTBITUQyL2RQVWhneUtRdz09" style="Vkc4US95bjkrMFVTYm16RjBzeWtMenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="进程CPU利用率" description="进程CPU利用率" unit="%"> 
        
                <IsDisplay displayOrder="NStlQzNGZVdNdzRIVkRUcE5nS1pVZz09">SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsDisplay>  
        
                <IsMonitor>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>TmpOT294bXcxcU9kL25HWkJ3bHQ4QT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>dWdaOUk3Zk9FY1V0ZWhURE5zNWhwWWhaeStvaWQzMitnUWllR1FieTMwOExrUlQ0WWRrWEZXU3ZDRWo4QWl3QQ==</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping>  
        
                <Thresholds> 
          
                    <Threshold operator="&lt;" defaultvalue="TFRoRnZuWXVEb09Ha1UzTXhmNlgwZz09" stateid="RUVYZjB6T2Iyc0xoQlF3NGNPN1NJdz09"/>  
          
                    <Threshold operator="&gt;=" defaultvalue="TFRoRnZuWXVEb09Ha1UzTXhmNlgwZz09" stateid="WkFkWXZpYksrNk9KeTc0VnRNeWd0QT09"/>  
          
                    <Threshold operator="&gt;=" defaultvalue="anY5QjVWaUdvd1FoSVNEN3NyVUhJdz09" stateid="dHdtUDg2T1FjR2RVN1BoR3dMd2EzUT09"/> 
        
                </Thresholds> 
      
            </Metric>  
      
      
            <Metric id="TmkvOWtlS0ttZ3BJREdVT3lnMThNdz09" style="Vkc4US95bjkrMFVTYm16RjBzeWtMenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="进程内存利用率" description="进程内存利用率" unit="%"> 
        
                <IsDisplay displayOrder="N0NONEJjbm9XK3ZKM0lsaktEakxyQT09">SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsDisplay>  
        
                <IsMonitor>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>TmpOT294bXcxcU9kL25HWkJ3bHQ4QT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>dWdaOUk3Zk9FY1V0ZWhURE5zNWhwWWhaeStvaWQzMitnUWllR1FieTMwOExrUlQ0WWRrWEZXU3ZDRWo4QWl3QQ==</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping>  
        
                <Thresholds> 
          
                    <Threshold operator="&lt;" defaultvalue="TFRoRnZuWXVEb09Ha1UzTXhmNlgwZz09" stateid="RUVYZjB6T2Iyc0xoQlF3NGNPN1NJdz09"/>  
          
                    <Threshold operator="&gt;=" defaultvalue="TFRoRnZuWXVEb09Ha1UzTXhmNlgwZz09" stateid="WkFkWXZpYksrNk9KeTc0VnRNeWd0QT09"/>  
          
                    <Threshold operator="&gt;=" defaultvalue="anY5QjVWaUdvd1FoSVNEN3NyVUhJdz09" stateid="dHdtUDg2T1FjR2RVN1BoR3dMd2EzUT09"/> 
        
                </Thresholds> 
      
            </Metric>  
      
            <!-- <Metric id="procMulStat" style="InformationMetric" name="进程状态" description="进程状态" unit=""> 
        <IsDisplay displayOrder="2039">true</IsDisplay>  
        <IsMonitor>true</IsMonitor>  
        <IsEdit>false</IsEdit>  
        <DefaultMonitorFreq>day1</DefaultMonitorFreq>  
        <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>  
        <IsAlert>true</IsAlert>  
        <DefaultFlapping>1</DefaultFlapping> 
      </Metric>  --> 
      
            <Metric id="THNLdjVDS2xFQ253L1VLclN6ODJNUT09" style="TDBUaHMrK3BZWXlhQmZoVXFZZERjenZjUUNzRDFFc09TRjVJUVVHUXpnYz0=" name="进程开始时间" description="进程开始时间" unit=""> 
        
                <IsDisplay displayOrder="My9JQzU4aGs3empReVdEMXpmT2puUT09">SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsDisplay>  
        
                <IsMonitor>SDRSWWdMQkdmdmZiTlU0OXdaMkhtQT09</IsMonitor>  
        
                <IsEdit>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsEdit>  
        
                <DefaultMonitorFreq>NHVBL0Y0NmhkYU50WHNzditxS3hYUT09</DefaultMonitorFreq>  
        
                <SupportMonitorFreq>SHNiL3VCVUVqMXVJSjFRdG1XaDNuQT09</SupportMonitorFreq>  
        
                <IsAlert>VlQ1MENXQzVkMjFRUHpXK3BJQ0lvQT09</IsAlert>  
        
                <DefaultFlapping>Z0w4SHRMSE00Y3NrTmVrcUwvallndz09</DefaultFlapping> 
      
            </Metric> 
    
        </Metrics>  
    
        <Properties> 
      
            <Property id="NFRRT3BMeEFmd3BkMWtsMEFYNEc0dz09" name="processId" metricid="NFRRT3BMeEFmd3BkMWtsMEFYNEc0dz09"/>  
      
            <Property id="K3A5eVhNYXd6RFpCeWlmVFY0bnJsQT09" name="processCommand" metricid="K3A5eVhNYXd6RFpCeWlmVFY0bnJsQT09"/> 
    
        </Properties>
    
        <Instantiation InstanceId="bUNNYWNjUXZzSGRlWUJBUzM3VHJWUVlPMmh5Sy9iamh5Zlh6cm84MTJFUT0=" InstanceName="K3A5eVhNYXd6RFpCeWlmVFY0bnJsQT09"/>   
  
    </Resource> 
</Capacity>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/tools/4.1docs/middleware/mwcics/resource.xml
<?xml version="1.0" encoding="UTF-8"?>

<Capacity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Resource.xsd">
    <SupportInfo>
        <SupportName>CICS</SupportName>
        <PreSupportVersion>CICS 7.1</PreSupportVersion>
        <ActualSupportVersion>CICS 7.1/SCO Unixware</ActualSupportVersion>
    </SupportInfo>
    <GlobalMetricSetting isEncrypt="FALSE" version="4.1.0">
        <GlobalIsEdit>false</GlobalIsEdit>
        <GlobalIsMonitor>true</GlobalIsMonitor>
        <GlobalDefaultMonitorFreq>day1</GlobalDefaultMonitorFreq>
        <GlobalsupportMonitorFreq>min1,min5,min10,hour1,day1</GlobalsupportMonitorFreq>
        <GlobalIsAlert>true</GlobalIsAlert>
        <GlobalDefaultFlapping>1</GlobalDefaultFlapping>
    </GlobalMetricSetting>
    <Resource id="MWCICS" category="CICS" icon="MWCICS.png" name="CICS Client" description="CICS Client">
        <Metrics>
            <Metric id="icmpDelayTime" style="PerformanceMetric" name="响应时间" description="响应时间" unit="ms">
                <IsDisplay displayOrder="1030">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="500" stateid="Normal"/>
                    <Threshold operator="&gt;" defaultvalue="1000" stateid="Minor"/>
                    <Threshold operator="&gt;" defaultvalue="5000" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="cpuRate" style="PerformanceMetric" name="CPU利用率" description="CPU利用率" unit="%">
                <IsDisplay displayOrder="1400">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="memRate" style="PerformanceMetric" name="内存利用率" description="内存利用率" unit="%">
                <IsDisplay displayOrder="2500">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="OperatingSystem" style="InformationMetric" name="操作系统" description="操作系统" unit="">
                <IsDisplay displayOrder="110">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="hostName" style="InformationMetric" name="主机名称" description="主机名称" unit="">
                <IsDisplay displayOrder="100">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="totalMemSize" style="InformationMetric" name="内存总容量" description="内存大小" unit="KB">
                <IsDisplay displayOrder="600">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="availability" style="AvailabilityMetric" name="CICS服务可用性" description="CICS服务可用性" unit="">
                <IsDisplay displayOrder="50">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min1</DefaultMonitorFreq>
                <SupportMonitorFreq>sec30,min1,min5,min10,min30,hour1</SupportMonitorFreq>
                <IsAlert>true</IsAlert>
                <DefaultFlapping>2</DefaultFlapping>
            </Metric>
            <Metric id="appCpuRate" style="PerformanceMetric" name="CICS CPU利用率" description="CICS CPU利用率" unit="%">
                <IsDisplay displayOrder="1500">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="appMemRate" style="PerformanceMetric" name="CICS 内存利用率" description="CICS 内存利用率" unit="%">
                <IsDisplay displayOrder="2600">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
        </Metrics>
        <Properties>
            <Property id="hostName" name="hostName" metricid="hostName"/>
            <Property id="availability" name="availability" metricid="availability"/>
            <Property id="totalMemSize" name="totalMemSize" metricid="totalMemSize"/>
        </Properties>
        <Instantiation InstanceId="availability" InstanceName="hostName"/>
    </Resource>
</Capacity>
