=== moutainhigh/stm-peng/stm_portal_3-master/capacity/tools/schema/Resource.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Capacity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SupportInfo" minOccurs="0"/>
				<xs:element ref="GlobalMetricSetting"/>
				<xs:element ref="Resource" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:keyref name="resourceIdKeyref" refer="resourceIdUnique">
			<xs:selector xpath=".//Resource"/>
			<xs:field xpath="@parentid"/>
		</xs:keyref>
		<xs:unique name="resourceIdUnique">
			<xs:selector xpath=".//Resource"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	<xs:element name="DefaultMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1"/>
				<xs:enumeration value="min5"/>
				<xs:enumeration value="min10"/>
				<xs:enumeration value="min30"/>
				<xs:enumeration value="hour1"/>
				<xs:enumeration value="hour2"/>
				<xs:enumeration value="day1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GlobalDefaultMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1"/>
				<xs:enumeration value="min5"/>
				<xs:enumeration value="min10"/>
				<xs:enumeration value="min30"/>
				<xs:enumeration value="hour1"/>
				<xs:enumeration value="hour2"/>
				<xs:enumeration value="day1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GlobalIsAlert" type="xs:boolean"/>
	<xs:element name="GlobalIsEdit" type="xs:boolean"/>
	<xs:element name="GlobalIsMonitor" type="xs:boolean"/>
	<xs:element name="GlobalDefaultFlapping" type="xs:integer"/>
	<xs:element name="DefaultFlapping" type="xs:integer"/>
	<xs:element name="GlobalMetricSetting">
		<xs:complexType>
			<xs:all>
				<xs:element ref="GlobalIsEdit"/>
				<xs:element ref="GlobalIsMonitor"/>
				<xs:element ref="GlobalDefaultMonitorFreq"/>
				<xs:element ref="GlobalsupportMonitorFreq"/>
				<xs:element ref="GlobalIsAlert"/>
				<xs:element ref="GlobalDefaultFlapping"/>
			</xs:all>
			<xs:attribute name="isEncrypt" type="xs:string" use="optional"/>
			<xs:attribute name="version" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GlobalsupportMonitorFreq" type="xs:string"/>
	<xs:element name="Instantiation">
		<xs:complexType>
			<xs:attribute name="InstanceId" type="xs:string" use="required"/>
			<xs:attribute name="InstanceName" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsDisplay">
		<xs:complexType mixed="true">
			<xs:attribute name="displayOrder" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsEdit" type="xs:boolean"/>
	<xs:element name="IsMonitor" type="xs:boolean"/>
	<xs:element name="IsAlert" type="xs:boolean"/>
	<xs:element name="Metric">
		<xs:complexType>
			<xs:all>
				<xs:element ref="IsDisplay" minOccurs="0"/>
				<xs:element ref="IsMonitor" minOccurs="0"/>
				<xs:element ref="IsEdit" minOccurs="0"/>
				<xs:element ref="DefaultMonitorFreq" minOccurs="0"/>
				<xs:element ref="SupportMonitorFreq" minOccurs="0"/>
				<xs:element ref="Thresholds" minOccurs="0"/>
				<xs:element ref="DefaultFlapping" minOccurs="0"/>
				<xs:element ref="IsAlert" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"></xs:minLength>
						<xs:maxLength value="20"></xs:maxLength>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="style" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PerformanceMetric"/>
						<xs:enumeration value="AvailabilityMetric"/>
						<xs:enumeration value="InformationMetric"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="unit" type="xs:string" use="required"/>
			<xs:attribute name="group" type="xs:string" use="optional"/>
			<xs:attribute name="isTable" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Metrics">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Metric" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="metricid" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Resource">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Metrics"/>
				<xs:element ref="Properties"/>
				<xs:element ref="Instantiation"/>
			</xs:all>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="category" type="xs:string"/>
			<xs:attribute name="icon" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="parentid" type="xs:string"/>
			<xs:attribute name="autodiscovery" type="xs:boolean"/>
		</xs:complexType>
		<xs:key name="metricIdKey">
			<xs:selector xpath=".//Metrics/Metric"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="metricIdKeyref" refer="metricIdKey">
			<xs:selector xpath=".//Propertys/Property"/>
			<xs:field xpath="@metricid"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="SupportMonitorFreq">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="min1,min5,hour1"/>
				<xs:enumeration value="min1,min5,hour1,day1"/>
				<xs:enumeration value="hour1,day1"/>
				<xs:enumeration value="hour1,hour2,day1"/>
				<xs:enumeration value="hour2,day1"/>
				<xs:enumeration value="min5,hour1"/>
				<xs:enumeration value="min5,hour1,day1"/>
				<xs:enumeration value="min5,min10,min30"/>
				<xs:enumeration value="min30,hour1"/>
				<xs:enumeration value="min30,hour1,hour2"/>
				<xs:enumeration value="sec30,min1,min5,min10,min30,hour1"/>
				<xs:enumeration value="min1,min5,min10,min30,hour1,day1"/>
				<xs:enumeration value="min1,min5,min10,min30,hour1,hour4,hour8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Thresholds">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Threshold" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Threshold">
		<xs:complexType>
			<xs:attribute name="operator" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value=">"/>
						<xs:enumeration value=">="/>
						<xs:enumeration value="&lt;>"/>
						<xs:enumeration value="&lt;"/>
						<xs:enumeration value="&lt;="/>
						<xs:enumeration value="="/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="defaultvalue" type="xs:string" use="optional"/>
			<xs:attribute name="stateid" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Indeterminate"/>
						<xs:enumeration value="Normal"/>
						<xs:enumeration value="Minor"/>
						<xs:enumeration value="Major"/>
						<xs:enumeration value="Critical"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupportInfo">
		<xs:complexType>
			<xs:all>
				<xs:element ref="SupportName"/>
				<xs:element ref="PreSupportVersion"/>
				<xs:element ref="ActualSupportVersion"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="SupportName" type="xs:string"/>
	<xs:element name="PreSupportVersion" type="xs:string"/>
	<xs:element name="ActualSupportVersion" type="xs:string"/>
</xs:schema>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/4.1docs/vm/XenHost/resource.xml
<?xml version="1.0" encoding="UTF-8"?>

<Capacity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Resource.xsd">
    <GlobalMetricSetting isEncrypt="FALSE" version="4.1.0">
        <GlobalIsEdit>false</GlobalIsEdit>
        <GlobalIsMonitor>true</GlobalIsMonitor>
        <GlobalDefaultMonitorFreq>day1</GlobalDefaultMonitorFreq>
        <GlobalsupportMonitorFreq>min1,min5,min10,hour1,day1</GlobalsupportMonitorFreq>
        <GlobalIsAlert>true</GlobalIsAlert>
        <GlobalDefaultFlapping>1</GlobalDefaultFlapping>
    </GlobalMetricSetting>
    <Resource id="XenHost" category="XenHosts" icon="XenHost.png" name="Xen服务器" description="Xen服务器">
        <Metrics>
            <Metric id="availability" style="AvailabilityMetric" name="可用性" description="XenServer.主机可用性:获取自身的连接与否状态" unit="">
                <IsDisplay displayOrder="1000">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min1</DefaultMonitorFreq>
                <SupportMonitorFreq>sec30,min1,min5,min10,min30,hour1</SupportMonitorFreq>
                <IsAlert>true</IsAlert>
                <DefaultFlapping>2</DefaultFlapping>
            </Metric>
            <Metric id="nameLabel" style="InformationMetric" name="服务器名称" description="服务器名称" unit="">
                <IsDisplay displayOrder="1010">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>hour1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="uuid" style="InformationMetric" name="uuid" description="uuid" unit="">
                <IsDisplay displayOrder="1020">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="hostname" style="InformationMetric" name="DNS主机名" description="DNS主机名" unit="">
                <IsDisplay displayOrder="1100">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="address" style="InformationMetric" name="地址" description="地址" unit="">
                <IsDisplay displayOrder="1110">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="sysUpTime" style="InformationMetric" name="连续运行时间" description="连续运行时间" unit="秒">
                <IsDisplay displayOrder="1120">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="cpuRate" style="PerformanceMetric" name="CPU利用率" description="CPU利用率" unit="%">
                <IsDisplay displayOrder="1400">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="memRate" style="PerformanceMetric" name="内存利用率" description="内存利用率" unit="%">
                <IsDisplay displayOrder="1410">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="90" stateid="Normal"/>
                    <Threshold operator="&gt;=" defaultvalue="90" stateid="Minor"/>
                    <Threshold operator="&gt;=" defaultvalue="95" stateid="Major"/>
                </Thresholds>
            </Metric>
            <Metric id="throughput" style="PerformanceMetric" name="吞吐量" description="吞吐量" unit="Bps">
                <IsDisplay displayOrder="1420">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min5</DefaultMonitorFreq>
                <SupportMonitorFreq>min1,min5,min10,min30,hour1,hour4,hour8</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
                <Thresholds>
                    <Threshold operator="&lt;" defaultvalue="100" stateid="Normal"/>
                    <Threshold operator="&gt;" defaultvalue="200" stateid="Minor"/>
                    <Threshold operator="&gt;" defaultvalue="400" stateid="Major"/>
                </Thresholds>
            </Metric>
        </Metrics>
        <Properties>
            <Property id="uuid" name="uuid" metricid="uuid"/>
            <Property id="nameLabel" name="nameLabel" metricid="nameLabel"/>
        </Properties>
        <Instantiation InstanceId="uuid" InstanceName="nameLabel"/>
    </Resource>
</Capacity>

=== moutainhigh/stm-peng/stm_portal_3-master/capacity/cap_libs/4.1docs/general/port/resource.xml
<?xml version="1.0" encoding="UTF-8"?>
<Capacity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="../../../schema/Resource.xsd">
    <GlobalMetricSetting>
        <GlobalIsEdit>false</GlobalIsEdit>
        <GlobalIsMonitor>true</GlobalIsMonitor>
        <GlobalDefaultMonitorFreq>day1</GlobalDefaultMonitorFreq>
        <GlobalsupportMonitorFreq>min1,min5,min10,hour1,day1</GlobalsupportMonitorFreq>
        <GlobalIsAlert>true</GlobalIsAlert>
        <GlobalDefaultFlapping>1</GlobalDefaultFlapping>
    </GlobalMetricSetting>
    <Resource id="TCPPort" category="Port" icon="port.png" name="Port" description="端口">
        <Metrics>
            <Metric id="Name" style="InformationMetric" name="端口名称" description="端口名称" unit="">
                <IsDisplay displayOrder="1000">false</IsDisplay>
                <IsMonitor>false</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="ip" style="InformationMetric" name="IP地址" description="IP地址" unit="">
                <IsDisplay displayOrder="1010">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="port" style="InformationMetric" name="端口号" description="端口号" unit="">
                <IsDisplay displayOrder="1020">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>day1</DefaultMonitorFreq>
                <SupportMonitorFreq>hour1,day1</SupportMonitorFreq>
                <IsAlert>false</IsAlert>
                <DefaultFlapping>1</DefaultFlapping>
            </Metric>
            <Metric id="availability" style="AvailabilityMetric" name="可用性" description="可用性" unit="">
                <IsDisplay displayOrder="1030">true</IsDisplay>
                <IsMonitor>true</IsMonitor>
                <IsEdit>false</IsEdit>
                <DefaultMonitorFreq>min1</DefaultMonitorFreq>
                <SupportMonitorFreq>sec30,min1,min5,min10,min30,hour1</SupportMonitorFreq>
                <IsAlert>true</IsAlert>
                <DefaultFlapping>2</DefaultFlapping>
            </Metric>
        </Metrics>
        <Properties>
            <Property id="Name" name="Name" metricid="Name"/>
            <Property id="ip" name="ip" metricid="ip"/>
            <Property id="port" name="port" metricid="port"/>
        </Properties>
        <Instantiation InstanceId="ip,port" InstanceName="Name"/>
    </Resource>
</Capacity>
